import { get, put } from './db.js';

const MAILBOX_PRESET_VERSION = 2;
const LEGACY_MAILBOX_PRESET_VERSION = 1;
const DEFAULT_CONTEXT_DEPTH = 80;
const MIN_CONTEXT_DEPTH = 20;
const MAX_CONTEXT_DEPTH = 160;

export const MAILBOX_TYPE_OPTIONS = [
  { value: 'auto', label: '自动' },
  { value: 'personal', label: '日常' },
  { value: 'check_in', label: '问候' },
  { value: 'apology', label: '道歉' },
  { value: 'invitation', label: '邀请' },
  { value: 'update', label: '近况' },
  { value: 'long_letter', label: '长信' },
  { value: 'practical', label: '事务' },
  { value: 'playful', label: '玩笑' },
];

export const MAILBOX_TYPE_BIAS_OPTIONS = [
  { value: 'natural', label: '自然选择' },
  { value: 'personal', label: '日常亲密' },
  { value: 'longform', label: '更常写长信' },
  { value: 'practical', label: '更克制实际' },
];

export const MAILBOX_SOURCE_OPTIONS = [
  { value: 'contact', label: '通讯录角色' },
  { value: 'forum', label: '论坛网友' },
  { value: 'stranger', label: '陌生消息与匿名网友' },
];

function clean(value = '', max = 0) {
  const text = String(value ?? '').trim();
  return max > 0 ? text.slice(0, max) : text;
}

function clampDepth(value) {
  const number = Math.round(Number(value));
  if (!Number.isFinite(number)) return DEFAULT_CONTEXT_DEPTH;
  return Math.max(MIN_CONTEXT_DEPTH, Math.min(MAX_CONTEXT_DEPTH, number));
}

export function normalizeMailboxType(value = '', { allowAuto = true } = {}) {
  const type = clean(value, 40).toLowerCase();
  const allowed = MAILBOX_TYPE_OPTIONS.map((row) => row.value);
  if (allowed.includes(type) && (allowAuto || type !== 'auto')) return type;
  return allowAuto ? 'auto' : 'personal';
}

export function mailboxTypeLabel(value = '') {
  const normalized = normalizeMailboxType(value);
  return MAILBOX_TYPE_OPTIONS.find((row) => row.value === normalized)?.label || '日常';
}

function normalizeMailboxSources(value = []) {
  const allowed = new Set(MAILBOX_SOURCE_OPTIONS.map((row) => row.value));
  const sources = [...new Set((Array.isArray(value) ? value : [value])
    .map((row) => clean(row, 40).toLowerCase())
    .filter((row) => allowed.has(row)))];
  return sources.length ? sources : ['contact'];
}

function clampAutoFetchInterval(value) {
  const number = Math.round(Number(value));
  if (!Number.isFinite(number)) return 24;
  return Math.max(1, Math.min(720, number));
}

function presetKey(userId = '', version = MAILBOX_PRESET_VERSION) {
  return `mailboxPreset:v${version}:${encodeURIComponent(clean(userId, 180) || 'guest')}`;
}

export function normalizeMailboxPreset(value = {}) {
  const source = value && typeof value === 'object' ? value : {};
  const bias = clean(source.typeBias, 40).toLowerCase();
  return {
    version: MAILBOX_PRESET_VERSION,
    contextDepth: clampDepth(source.contextDepth),
    typeBias: MAILBOX_TYPE_BIAS_OPTIONS.some((row) => row.value === bias) ? bias : 'natural',
    customInstruction: clean(source.customInstruction, 4000),
    autoFetchEnabled: source.autoFetchEnabled === true,
    autoFetchIntervalHours: clampAutoFetchInterval(source.autoFetchIntervalHours),
    autoFetchSources: normalizeMailboxSources(source.autoFetchSources),
    lastAutoGeneratedAt: Math.max(0, Number(source.lastAutoGeneratedAt || 0) || 0),
    lastAutoAttemptAt: Math.max(0, Number(source.lastAutoAttemptAt || 0) || 0),
    updatedAt: Math.max(0, Number(source.updatedAt || 0) || 0),
  };
}

export async function loadMailboxPreset(userId = '') {
  const row = await get(presetKey(userId)).catch(() => null);
  if (row?.value) return normalizeMailboxPreset(row.value);
  const legacy = await get(presetKey(userId, LEGACY_MAILBOX_PRESET_VERSION)).catch(() => null);
  return normalizeMailboxPreset(legacy?.value);
}

export async function saveMailboxPreset(userId = '', patch = {}) {
  const current = await loadMailboxPreset(userId);
  const next = normalizeMailboxPreset({ ...current, ...(patch || {}), updatedAt: Date.now() });
  await put({ key: presetKey(userId), value: next });
  return next;
}
